apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: kafka
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 18.4.4
    helm:
      releaseName: kafka
      values: |
        auth:
          sasl:
            mechanism: scram-sha-256
            jaas:
              clientUsers:
                - user
              clientPasswords:
                - userpassword
  destination:
    namespace: kafka
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
