apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv-volume
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/mariadb
