apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment/redis.yaml
  - service/redis.yaml

configMapGenerator:
  - name: config
    files:
      - redis.conf

images:
  - name: redis
    newTag: 5.0.4
