apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment/mariadb.yaml
  - persistant-volume/persistant-volume.yaml
  - persistant-volume/persistant-volume-claim.yaml
  - service/mariadb.yaml

images:
  - name: mariadb
    newTag: "10.3"
