apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  project: default
  source:
    chart: argo-workflows
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.22.13
    helm:
        values: |
            server:
                extraArgs:
                    - --auth-mode=server
                ingress:
                    enabled: true
                    ingressClassName: traefik
                    hosts:
                        - workflow.svc.localhost
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
